sudo: required
services:
  - docker

cache:
  directories:
    - $HOME/.cache

language: rust
rust:
  - nightly

env:
  matrix:
    - PACK=1 OS=debian DIST=jessie ARCH=i386
    - PACK=1 OS=debian DIST=jessie ARCH=x86_64
  on:
    tags: true

script:
  - if [ "$PACK" == "1" ]; then git clone https://github.com/packpack/packpack.git packpack; fi
  - if [ "$PACK" == "1" ]; then packpack/packpack; fi

deploy:
  provider: packagecloud
  username: ${PACKAGECLOUD_USER}
  repository: ${PACKAGECLOUD_REPO}
  token: ${PACKAGECLOUD_TOKEN}
  dist: ${OS}/${DIST}
  package_glob: build/*.deb
  skip_cleanup: true
  on:
    tags: true
    condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
