[package]
name = "bloom"
version = "0.0.3"
description = "HTTP REST API caching middleware, to be used between load balancers and REST API workers."
readme = "README.md"
license = "MPL2"
homepage = "https://github.com/valeriansaliou/bloom"
repository = "https://github.com/valeriansaliou/bloom.git"
keywords = ["rest", "cache", "dos", "ddos", "scale", "infrastructure", "performance", "http", "speed"]
categories = ["proxy", "http", "api"]
publish = false
authors = ["Valerian Saliou <valerian@valeriansaliou.name>"]

[badges]
travis-ci = { repository = "valeriansaliou/bloom", branch = "master" }
coveralls = { repository = "valeriansaliou/bloom", branch = "master", service = "github" }

[dependencies]
log = "0.3"
rust-ini = "0.10"
clap = "2.25"
lazy_static = "0.2"
futures = "0.1"
httparse = "1.2"
hyper = "0.11"
tokio-core = "0.1"
r2d2 = "0.7"
r2d2_redis = "0.6"
redis = "0.8"
farmhash = "1.1"
rand = "0.3"

[dev-dependencies]

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true

[profile.release]
opt-level = "s"
lto = true
debug = false
debug-assertions = false
